# Generated by Django 3.2.6 on 2021-08-28 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['https://youtu.be/'])], verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
