# Generated by Django 3.1.1 on 2021-09-04 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='サムネイル')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='videos.course', verbose_name='コース'),
            preserve_default=False,
        ),
    ]
